language: node_js
node_js:
- '0.12'
before_script:
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g bower grunt-cli
- gem install sass
- bower install
services: mongodb
before_install:
- openssl aes-256-cbc -K $encrypted_a7a13d2aff9e_key -iv $encrypted_a7a13d2aff9e_iv
  -in encrypt.tar.enc -out encrypt.tar -d
- tar xvf encrypt.tar
after_success:
- cat ./coverage/{client,server}/unit/lcov.info > ./coverage/lcov.info && cat ./coverage/lcov.info
  | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage/lcov.info
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa
- grunt deploy
notifications:
  slack:
    secure: YtbLLLfyBoWWc/BJFAeqvSIOKtXGaNDnwdsAO+sWV47UO8SNnU0EYMy8kE6f59SNIlr/tDp7IcDUS/OdVrb7dFuHQTkisedCWkaT2MH0DqXLQIas61hwadIiDEaJISpEp1GTS2T1Jp796oiW74xXcXCXtMLGPGSHnioMh3FdUJWT5cgu9Htg0y8lfeoRGgqMY4nsBgjcNpRESinEhEjVYLZjJtYJJBkjYI8FgqLX0smHicI/v39sD2W3o8uy4/6WdseEM6vHTbsnLTXsnvFpuMss1JXxV1GOtcummbCEgNWkT56W2Ijjy920fCCdNF7/eirJl2qsliuEr6NLsHKqzvam3R81LEc9fN1qRYsDiCoi1xpPrZyTuW65/c00o+V9JlaK/cOCV5ifqY7oTaWEYLo/wGr6RhMxbKtcfYcQMsW+jwMkwijy+WGKFmnEuMHNWwxiTMZu+kwo01OPZVo0naxI5ulLMzr5e6hIWHBN4GTCzmWR/NYCH3WNfyBRInv4amyONwLnGLEbymRjqYPlsIual89xcGi+PzRvhWI6yMq3+699xF+a+/k5raV1QGJHRmH5ypB0HHI8XD98NR4qHpO73v0hBwLkKmNrKplYLbElt9nHXTarv5LEOLAGnfYI/tcHP+UTPWzQdG1LE4VC2coAlKeMpQyl7qhhZMCPyTE=
