nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - mongo:mongo
node2:
    build: ./node
    links:
        - mongo:mongo
node3:
    build: ./node
    links:
        - mongo:mongo
mongo:
    build: ./mongo
    ports:
        - "27017:27017"
