nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - mongo:mongo
mongo:
    build: ./mongo
    ports:
        - "27017:27017"
