nginx:
  build: ./nginx
  links:
    - node1:node1
  ports:
    - "80:80"
node1:
  build: ./node
  links:
    - mongo:mongo
    - rabbit:rabbit
  ports:
    - "8080"
mongo:
  build: ./mongo
  ports:
    - "27017:27017"
  volumes:
    - ./mongo/data:/data/db/seeds
rabbit:
  build: ./rabbit
  ports:
    - "5672:5672"

